import { Header } from '@/components/header'
import './globals.css'
import { Saira } from 'next/font/google'
import DefaultProviders from '@/components/default-providers'

const saira = Saira({
  weight: ['300', '400', '500', '600'],
  subsets: ['latin'],
  display: 'swap'
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={saira.className}>
      <body>
        <DefaultProviders>
          <Header />
          {children}
        </DefaultProviders>
      </body>
    </html>
  )
}